// This file is automatically generated.

interface CssExports {
  'top-button': string;
  'top-button-danger': string;
  'top-button-primary': string;
  'topButton': string;
  'topButtonDanger': string;
  'topButtonPrimary': string;
}

declare var cssExports: CssExports;
export = cssExports;
